### ISSUE TITLE
Is the file useable currently?

### ISSUE THREAD

**Issue by Giddius** [ianbanks/arma_3_substance_shader#5]
I have seen the issue about Base color vs Diffuse and also seen merges afterwards and specific mentioning the issue. it is still base color in the file of the main branch (also only branch). Is there a reason? should I manually switch out all instances of Base color? 

also how are the extra channels intended to be used? only at the export phase or do they also have an impact on the preview?

Also is this still maintainend?

**Comment by Mickyleitor** [comment]
@Giddius Looks like there is no one watching this repo anymore ... But you could navigate though [forks](https://github.com/ianbanks/arma_3_substance_shader/network) and see what others did

**Comment by Giddius** [comment]
thank you very much for the answer,already did that, but I am not that versed in the syntax of the shader to see whats working or even change it. I also found a workaround so I wont have to use the shader. Was just a hail mary of seeing if there is still a maintainer.
again thank you for the answer though, seriously appreciate it!

**Comment by ianbanks** [comment]
Sorry for the delay in addressing this, I hadn't noticed the lack of notifications on this project.

The use of Base Colour versus Diffuse depends on your work flow to some extent, and since most people I've worked with are coming across from PBR Metal-Rough, "Base Colour" (as it is in the current version) is more convenient, even though technically "Diffuse" is more correct for super. The two channels behave identically in SP though, and custom shaders like this one can use them in any way they wish. There's no reason to swap if "Base Colour" is working in your process.

All of the extra channels mentioned in the .glsl affect the preview, with the exception of the direct shadow channel.
